### ISSUE TITLE
The parahphaser is not working on sentences when there's no predicate

### ISSUE THREAD

**Issue by DrMatters** [avidale/dependency-paraphraser#1]
For example: 'где ближайший магазин продуктов от меня' - question for a smart assistant
The paraphraser returns: '' (empty string)

**Comment by avidale** [comment]
@DrMatters, thank you very much for reporting this bug!

The error was due to the somewhat unpredictable format of dependency trees somewhat produced by Natasha (sometimes they refer to the token #-1 as the tree root, sometimes the root is one of the actual tokens, sometimes there are several roots, sometimes the parse graphs are cyclic...). 

Now I have fixed this error with some defensive programming. You can try it after updating the package to 0.0.4:

```
# pip install dependency-paraphraser>=0.0.4
import dependency_paraphraser.natasha
import random
random.seed(42)
text =  'где ближайший магазин продуктов от меня'
for i in range(3):
    print(dependency_paraphraser.natasha.paraphrase(text, tree_temperature=2))
```
